[package]
name = "opencvvideo"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "qr"
path = "src/bin/qr.rs"

[[bin]]
name = "video_facedetect"
path = "src/bin/video_facedetect.rs"

[dependencies]
opencv = "0.92.0"
